/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/commitments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Commitments */
        get: operations["list_commitments_commitments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assertions/{assertion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect */
        get: operations["inspect_assertions__assertion_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assertions/{assertion_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm */
        post: operations["confirm_assertions__assertion_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assertions/{assertion_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss */
        post: operations["dismiss_assertions__assertion_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assertions/{assertion_id}/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Correct */
        post: operations["correct_assertions__assertion_id__correct_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assertions/{assertion_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Status */
        post: operations["set_status_assertions__assertion_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Home
         * @description What changed since the previous visit, what needs attention, and what the user told us.
         */
        get: operations["home_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Visit
         * @description Called when the app comes to the foreground. Moves the "since last visit" marker.
         */
        post: operations["record_visit_visits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/briefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Brief */
        post: operations["generate_brief_briefs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/briefs/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Brief */
        get: operations["latest_brief_briefs_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notifications */
        get: operations["notifications_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Notifications Read */
        post: operations["mark_notifications_read_notifications_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Event */
        post: operations["record_event_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssertionDetail */
        AssertionDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** What */
            what: string;
            /** Commitment Type */
            commitment_type: string | null;
            /** Direction */
            direction: string | null;
            /** Committed By */
            committed_by: string | null;
            /** Committed To */
            committed_to: string | null;
            /** Due */
            due: string | null;
            /** Overdue */
            overdue: boolean;
            /** Status */
            status: string | null;
            /** Origin */
            origin: string;
            /** Review */
            review: string;
            /** Confidence */
            confidence: string;
            /** Evidence Quote */
            evidence_quote: string;
            /** Has Conflict */
            has_conflict: boolean;
            source: components["schemas"]["SourceSummary"];
            /** Kind */
            kind: string;
            /** Subject */
            subject: string;
            /** Predicate */
            predicate: string;
            /** Extraction Method */
            extraction_method: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Context Before */
            context_before: string;
            /** Context Quote */
            context_quote: string;
            /** Context After */
            context_after: string;
            /** Source Suspicious */
            source_suspicious: boolean;
            /** Related */
            related: components["schemas"]["RelatedAssertion"][];
        };
        /** BriefItem */
        BriefItem: {
            kind: components["schemas"]["ItemKind"];
            /**
             * Assertion Id
             * Format: uuid
             */
            assertion_id: string;
            /** Other Assertion Id */
            other_assertion_id?: string | null;
            /** Subject */
            subject: string;
            /** Predicate */
            predicate: string;
            /** Value */
            value: string;
            /** Previous Value */
            previous_value?: string | null;
            /** Due */
            due?: string | null;
            /**
             * Overdue
             * @default false
             */
            overdue: boolean;
            /** Is Fact */
            is_fact: boolean;
            /** Confidence */
            confidence: string;
            /** Evidence Quote */
            evidence_quote: string;
            /** Other Evidence Quote */
            other_evidence_quote?: string | null;
            /** Source Label */
            source_label: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /** BriefView */
        BriefView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Period */
            period: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Covers Since
             * Format: date-time
             */
            covers_since: string;
            /** Items */
            items: components["schemas"]["WrittenItem"][];
        };
        /** CommitmentItem */
        CommitmentItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** What */
            what: string;
            /** Commitment Type */
            commitment_type: string | null;
            /** Direction */
            direction: string | null;
            /** Committed By */
            committed_by: string | null;
            /** Committed To */
            committed_to: string | null;
            /** Due */
            due: string | null;
            /** Overdue */
            overdue: boolean;
            /** Status */
            status: string | null;
            /** Origin */
            origin: string;
            /** Review */
            review: string;
            /** Confidence */
            confidence: string;
            /** Evidence Quote */
            evidence_quote: string;
            /** Has Conflict */
            has_conflict: boolean;
            source: components["schemas"]["SourceSummary"];
        };
        /** Correction */
        Correction: {
            /** What */
            what?: string | null;
            /** Due */
            due?: string | null;
            /**
             * Clear Due
             * @default false
             */
            clear_due: boolean;
            /** Committed By */
            committed_by?: string | null;
            /** Committed To */
            committed_to?: string | null;
        };
        /** EventIn */
        EventIn: {
            /** Name */
            name: string;
            /** Subject Id */
            subject_id?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
        };
        /** Home */
        Home: {
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /** What Changed */
            what_changed: components["schemas"]["WrittenItem"][];
            /** Needs Attention */
            needs_attention: components["schemas"]["CommitmentItem"][];
            /** Needs Attention Total */
            needs_attention_total: number;
            /** Remembered */
            remembered: components["schemas"]["CommitmentItem"][];
            /** Unread Notifications */
            unread_notifications: number;
        };
        /**
         * ItemKind
         * @enum {string}
         */
        ItemKind: "due_soon" | "changed" | "conflict" | "possible_commitment" | "consumer" | "remembered";
        /** NotificationView */
        NotificationView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Deep Link */
            deep_link: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Read */
            read: boolean;
        };
        /** RelatedAssertion */
        RelatedAssertion: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Relation */
            relation: string;
            /** What */
            what: string;
            /** Due */
            due: string | null;
            /** Evidence Quote */
            evidence_quote: string;
            source: components["schemas"]["SourceSummary"];
        };
        /** SourceSummary */
        SourceSummary: {
            /** Kind */
            kind: string;
            /** Sender Name */
            sender_name: string | null;
            /** Sender Address */
            sender_address: string | null;
            /** Subject */
            subject: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /** StatusChange */
        StatusChange: {
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WrittenItem */
        WrittenItem: {
            item: components["schemas"]["BriefItem"];
            /** Headline */
            headline: string;
            /** Why It Matters */
            why_it_matters: string;
            /** Suggested Next Step */
            suggested_next_step?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_commitments_commitments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitmentItem"][];
                };
            };
        };
    };
    inspect_assertions__assertion_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assertion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssertionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_assertions__assertion_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assertion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssertionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_assertions__assertion_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assertion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssertionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_assertions__assertion_id__correct_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assertion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Correction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssertionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_status_assertions__assertion_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assertion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssertionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    home_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Home"];
                };
            };
        };
    };
    record_visit_visits_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    generate_brief_briefs_post: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_brief_briefs_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefView"];
                };
            };
        };
    };
    notifications_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationView"][];
                };
            };
        };
    };
    mark_notifications_read_notifications_read_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    record_event_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
