"""slice 2 and review fixes

Revision ID: 0003
Revises: 0002
"""

from alembic import op
import sqlalchemy as sa


revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "briefs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("period", sa.String(length=16), nullable=False),
        sa.Column("covers_since", sa.DateTime(timezone=True), nullable=False),
        sa.Column("writer_version", sa.String(length=64), nullable=False),
        sa.Column("items", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_briefs_user_id"), "briefs", ["user_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("deep_link", sa.String(length=200), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "product_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=48), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_events_name"), "product_events", ["name"], unique=False)
    op.create_index(op.f("ix_product_events_user_id"), "product_events", ["user_id"], unique=False)
    op.add_column(
        "assertion_relations",
        sa.Column("made_by", sa.String(length=16), nullable=False, server_default="pipeline"),
    )
    op.add_column("assertions", sa.Column("quote_hash", sa.String(length=64), nullable=True))
    # Existing rows get a hash of the stored quote. New rows hash the normalized quote, so a
    # pre-existing row whose quote contains unusual whitespace is re-created on the next run.
    op.execute(
        "UPDATE assertions SET quote_hash = encode(sha256(convert_to(evidence_quote, 'UTF8')), 'hex')"
    )
    op.alter_column("assertions", "quote_hash", nullable=False)
    op.add_column(
        "assertions", sa.Column("ordinal", sa.Integer(), nullable=False, server_default="0")
    )
    op.drop_constraint(
        op.f("assertions_source_id_kind_evidence_quote_extraction_method__key"),
        "assertions",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_assertions_identity", "assertions", ["source_id", "kind", "quote_hash", "ordinal"]
    )
    op.drop_constraint(op.f("jobs_kind_key_key"), "jobs", type_="unique")
    op.add_column("users", sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("previous_seen_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "previous_seen_at")
    op.drop_column("users", "last_seen_at")
    op.create_unique_constraint(
        op.f("jobs_kind_key_key"), "jobs", ["kind", "key"], postgresql_nulls_not_distinct=False
    )
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("uq_assertions_identity", "assertions", type_="unique")
    op.create_unique_constraint(
        op.f("assertions_source_id_kind_evidence_quote_extraction_method__key"),
        "assertions",
        ["source_id", "kind", "evidence_quote", "extraction_method", "prompt_version"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("assertions", "ordinal")
    op.drop_column("assertions", "quote_hash")
    op.drop_column("assertion_relations", "made_by")
    op.drop_index(op.f("ix_product_events_user_id"), table_name="product_events")
    op.drop_index(op.f("ix_product_events_name"), table_name="product_events")
    op.drop_table("product_events")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_briefs_user_id"), table_name="briefs")
    op.drop_table("briefs")
    # ### end Alembic commands ###
