"""connections

Revision ID: 0004
Revises: 0003
"""

from alembic import op
import sqlalchemy as sa


revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("connector", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cursor", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "connector"),
    )
    op.create_index(op.f("ix_connections_user_id"), "connections", ["user_id"], unique=False)
    op.add_column(
        "sources",
        sa.Column("connector", sa.String(length=32), nullable=False, server_default="manual"),
    )
    op.create_index(op.f("ix_sources_connector"), "sources", ["connector"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sources_connector"), table_name="sources")
    op.drop_column("sources", "connector")
    op.drop_index(op.f("ix_connections_user_id"), table_name="connections")
    op.drop_table("connections")
    # ### end Alembic commands ###
