"""app bound login codes

Revision ID: 0006
Revises: 0005
"""

from alembic import op
import sqlalchemy as sa


revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Both tables hold rows that live for minutes. Clearing them is simpler and safer than
    # inventing a challenge for an attempt already in flight.
    op.execute("DELETE FROM login_codes")
    op.execute("DELETE FROM oauth_states")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("login_codes", sa.Column("app_challenge", sa.String(length=64), nullable=False))
    op.add_column("oauth_states", sa.Column("app_challenge", sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oauth_states", "app_challenge")
    op.drop_column("login_codes", "app_challenge")
    # ### end Alembic commands ###
