"""notification sequence

Revision ID: 0008
Revises: 0007
"""

from alembic import op
import sqlalchemy as sa


revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications",
        sa.Column("sequence", sa.Integer(), sa.Identity(always=False), nullable=False),
    )
    op.create_unique_constraint("notifications_sequence_key", "notifications", ["sequence"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("notifications_sequence_key", "notifications", type_="unique")
    op.drop_column("notifications", "sequence")
    # ### end Alembic commands ###
