"""consent at start

Revision ID: 0011
Revises: 0010
"""

from alembic import op
import sqlalchemy as sa


revision = "0011"
down_revision = "0010"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Attempts in flight predate consent-at-start; they live minutes and are simply dropped.
    op.execute("DELETE FROM oauth_states")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("oauth_states", sa.Column("terms_version", sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oauth_states", "terms_version")
    # ### end Alembic commands ###
